-- ==============================================================================
-- Cash Bill Schema for Nagarathnamma Screen & Offset Printing
-- Run this in Supabase SQL Editor: https://ifxjekxawcnczezyjkrd.supabase.co
-- ==============================================================================

-- 1. Create bills table
CREATE TABLE IF NOT EXISTS public.bills (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    bill_no BIGINT GENERATED BY DEFAULT AS IDENTITY,
    custom_bill_no TEXT,
    bill_date DATE NOT NULL DEFAULT CURRENT_DATE,
    customer_name TEXT NOT NULL,
    customer_phone TEXT,
    customer_address TEXT,
    items JSONB NOT NULL DEFAULT '[]'::jsonb,
    subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    advance NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    total_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    amount_in_words TEXT,
    payment_mode TEXT DEFAULT 'Cash',
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2. Create company_settings table
CREATE TABLE IF NOT EXISTS public.company_settings (
    id TEXT PRIMARY KEY DEFAULT 'default',
    company_name TEXT NOT NULL DEFAULT 'Nagarathnamma',
    tagline TEXT NOT NULL DEFAULT 'SCREEN & OFFSET PRINTING',
    phone TEXT NOT NULL DEFAULT '9986073931',
    address TEXT NOT NULL DEFAULT '# 72, 4th Cross Road, Vidyaranyapura, Bengaluru – 560 097.',
    bank_name TEXT NOT NULL DEFAULT 'IDBI Bank',
    account_name TEXT NOT NULL DEFAULT 'K N NAGARATHNAMMA',
    account_no TEXT NOT NULL DEFAULT '0363104000056179',
    branch TEXT NOT NULL DEFAULT 'R.T. Nagar',
    ifsc_code TEXT NOT NULL DEFAULT 'IBKL0000363',
    next_bill_no BIGINT DEFAULT 1,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Insert default company settings if not exists
INSERT INTO public.company_settings (id, company_name, tagline, phone, address, bank_name, account_name, account_no, branch, ifsc_code)
VALUES (
    'default',
    'Nagarathnamma',
    'SCREEN & OFFSET PRINTING',
    '9986073931',
    '# 72, 4th Cross Road, Vidyaranyapura, Bengaluru – 560 097.',
    'IDBI Bank',
    'K N NAGARATHNAMMA',
    '0363104000056179',
    'R.T. Nagar',
    'IBKL0000363'
)
ON CONFLICT (id) DO NOTHING;

-- 3. Enable Row Level Security (RLS) and allow public read/write for anon API
ALTER TABLE public.bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_settings ENABLE ROW LEVEL SECURITY;

-- Allow public access with anon key (so mobile & PC can sync without complex login)
CREATE POLICY "Allow public read bills" ON public.bills FOR SELECT USING (true);
CREATE POLICY "Allow public insert bills" ON public.bills FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update bills" ON public.bills FOR UPDATE USING (true);
CREATE POLICY "Allow public delete bills" ON public.bills FOR DELETE USING (true);

CREATE POLICY "Allow public read settings" ON public.company_settings FOR SELECT USING (true);
CREATE POLICY "Allow public update settings" ON public.company_settings FOR UPDATE USING (true);
CREATE POLICY "Allow public insert settings" ON public.company_settings FOR INSERT WITH CHECK (true);

-- 4. Enable Realtime Publications for instant sync across devices
ALTER PUBLICATION supabase_realtime ADD TABLE public.bills;
ALTER PUBLICATION supabase_realtime ADD TABLE public.company_settings;
